# Generated by Django 3.1.4 on 2020-12-22 01:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=30, unique=True, verbose_name='color')),
            ],
            options={
                'verbose_name': 'Color Producto',
                'verbose_name_plural': 'Colores',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre del producto')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion del producto')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Cantidad en almacen')),
                ('price', models.FloatField(default=0)),
                ('discount_price', models.FloatField(default=0)),
                ('image_main', models.URLField(blank=True)),
                ('image', models.URLField(blank=True)),
                ('anulate', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('offer', models.BooleanField(blank=True, default=False, verbose_name='En oferta')),
                ('discount', models.PositiveIntegerField(blank=True, default=0, verbose_name='Descuento')),
                ('in_home', models.BooleanField(default=False)),
                ('slug', models.SlugField(editable=False, max_length=300)),
                ('color', models.ManyToManyField(to='product.Colors')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='nombre')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
            },
        ),
    ]
